name: Encrypt Images

on: [push]

jobs:
  encrypt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        # 如果有依賴可以在這裡安裝
        # pip install -r requirements.txt

    - name: Encrypt PNG Image
      run: python pngencode.py

    - name: Commit and Push Encrypted Image
      run: |
        git config --local user.email "weitsunglin@github.com"
        git config --local user.name "GitHub Action"
        git add test.png
        git commit -m "Encrypt test.png" || echo "No changes to commit"
        git push
